# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='image_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
