# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_address', models.CharField(max_length=500, null=True)),
                ('gathered_at', models.DateTimeField(verbose_name='time gathered')),
            ],
        ),
        migrations.CreateModel(
            name='Photon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_association', models.CharField(max_length=150)),
                ('last_connection', models.DateTimeField(null=True)),
                ('location_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('units', models.CharField(max_length=50)),
                ('photon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Photon')),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='photon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Photon'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Sensor'),
        ),
    ]
