# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160408_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_address', models.CharField(max_length=500, null=True)),
                ('gathered_at', models.DateTimeField(verbose_name='time gathered')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Sensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='image_address',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='photon_id',
        ),
    ]
